name: my test code
on: push
jobs: 
  job_one:
      name: get the cache
      runs-on: ubuntu-latest
      steps:
        - name: ls
          id: first
          run: ls
        - name: cd
          id: second
          run: cd ..
        - name: ls
          id: third
          run: ls
            
          
          
      
      
