name: my test code
on: push
jobs: 
  job_one:
      name: get the cache
      runs-on: ubuntu-latest
      steps:
        #先获取第一页的页面源代码
        - name: get source code 
          id: one 
          env: 
            URL: https://www.hostloc.com/forum-45-1.html
          run: curl -o source.html URL
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: source
            path: source.html
            
          
          
      
      
